WITH RENTAL_HISTORY AS (
    SELECT *, 
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
        ELSE "1"
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
SELECT HISTORY.HISTORY_ID, 
    ROUND((DATEDIFF(history.END_DATE, history.START_DATE) + 1) * CAR.DAILY_FEE
    * (1 - ifnull(dc_plan.discount_rate, 0) / 100 )) AS FEE
FROM RENTAL_HISTORY history 
JOIN CAR_RENTAL_COMPANY_CAR car ON CAR.CAR_ID = history.CAR_ID
LEFT JOIN (SELECT DURATION_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭") DC_PLAN  -- DC_PLAN테이블에는 7일미만인게 없기 때문에 "LEFT" 조인해야함!
ON history.duration_type = DC_PLAN.duration_type
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
